In [1]:
import pandas as pd
dataframe = pd.read_excel('https://github.com/mapossum/qmsa/blob/master/data/workbook-data-v2.xlsx?raw=true',sheet_name=1)
dataframe

,NAME,Electric Consumption (KWH),Births per 1000 in population,Children born per woman,GDP - Per Capita (in US Dollars),Life Expectancy at Birth (2012)
0,Afghanistan,2489.00,38.84,5.43,1100.0,61.0
1,Angola,4592.00,38.97,5.43,6300.0,51.0
2,Albania,4551.00,12.73,1.50,10700.0,77.0
3,United Arab Emirates,85170.00,15.54,2.36,29900.0,77.0
4,Argentina,111100.00,16.88,2.25,18600.0,76.0
5,Armenia,5800.00,13.92,1.64,6300.0,74.0
6,Australia,213500.00,12.19,1.77,43000.0,82.0
7,Austria,63800.00,8.76,1.43,42600.0,81.0
8,Azerbaijan,20290.00,16.96,1.91,10800.0,71.0
9,Burundi,221.40,42.33,6.14,600.0,54.0
10,Belgium,84680.00,9.99,1.65,37800.0,80.0
11,Benin,870.10,36.51,5.04,1600.0,59.0
12,Burkina Faso,773.10,42.42,5.93,1500.0,56.0
13,Bangladesh,38890.00,21.61,2.45,2100.0,70.0
14,Bulgaria,30460.00,8.92,1.44,14400.0,74.0
15,United States,3886000.00,13.42,2.01,52800.0,79.0
16,Bosnia and Herzegovina,12620.00,8.89,1.26,8300.0,76.0
17,Belarus,31740.00,10.86,1.47,16100.0,72.0
18,Belize,630.00,25.14,3.02,8800.0,74.0
19,Bolivia,6944.00,23.28,2.80,5500.0,67.0
20,Brazil,455800.00,14.72,1.79,12100.0,74.0
21,Bhutan,1680.00,18.12,2.02,7000.0,68.0
22,Botswana,3118.00,21.34,2.37,16400.0,47.0
23,Central African Republic,148.80,35.45,4.46,700.0,49.0
24,Canada,499900.00,10.29,1.59,43100.0,81.0
25,Switzerland,58970.00,10.48,1.54,54800.0,83.0
26,Chile,53930.00,13.97,1.84,19100.0,80.0
27,China,5322000.00,12.17,1.55,9800.0,75.0
28,CÃ´te d'Ivoire,NaN,NaN,NaN,NaN,NaN
29,Cameroon,5181.00,36.58,4.82,2400.0,55.0
...,...,...,...,...,...,...
136,Serbia,28040.00,9.13,1.42,11100.0,75.0
137,Suriname,1423.00,16.73,2.01,12900.0,71.0
138,Slovakia,26270.00,10.01,1.39,24700.0,NaN
139,Slovenia,12660.00,8.54,1.33,27400.0,80.0
140,Sweden,136000.00,11.92,1.88,40900.0,82.0
141,Swaziland,1058.00,25.18,2.88,5700.0,49.0
142,Syria,35610.00,22.76,2.68,5100.0,75.0
143,Chad,91.14,37.29,4.68,2500.0,51.0
144,Togo,676.10,34.52,4.53,1100.0,56.0
145,Thailand,169400.00,11.26,1.50,9900.0,74.0
146,Tajikistan,16090.00,24.99,2.76,2300.0,67.0
147,Turkmenistan,17080.00,19.46,2.10,9700.0,65.0
148,Timor-Leste,67.59,34.48,5.11,21400.0,67.0
149,Tunisia,13290.00,16.90,2.00,9900.0,75.0
150,Turkey,170400.00,16.86,2.08,15300.0,75.0
151,Taiwan,242200.00,8.55,1.11,39600.0,NaN
152,Tanzania,3403.00,36.82,4.95,1700.0,61.0
153,Uganda,2192.00,44.17,5.97,1500.0,59.0
154,Ukraine,175300.00,9.41,1.30,7400.0,71.0
155,Uruguay,7960.00,13.18,1.84,16600.0,77.0
156,France,462900.00,12.49,2.08,35700.0,83.0
157,Uzbekistan,44510.00,17.02,1.80,3800.0,68.0
158,Venezuela,85050.00,19.42,2.35,13600.0,74.0
159,Thailand,169400.00,11.26,1.50,9900.0,74.0
160,Vanuatu,51.15,25.69,3.36,4800.0,71.0
161,Yemen,5515.00,31.02,4.09,2500.0,NaN
162,South Africa,234200.00,18.94,2.23,11500.0,56.0
163,Zambia,7960.00,42.46,5.76,1800.0,57.0
164,Zimbabwe,12570.00,32.47,3.56,600.0,58.0
165,Lebanon,14190.00,14.80,1.74,15800.0,80.0